### ISSUE TITLE
sunset and sunrise times don't work as expected

### ISSUE THREAD

**Issue by themightyoarfish** [nightsense/night-and-day#1] opened 2017-10-29 18:01 UTC
So besides Vundle, I have only this in my `.vimrc`:
```
let g:nd_themes = [
    \ ['sunrise+0', 'solarized', 'light'],
    \ ['sunset+0', 'solarized', 'dark'],
\]

let g:nd_latitude = '50'
```

`:call NdSchedule()`  prints
```
THEME SCHEDULE
==============

start time     theme name
----------     ----------
16:42          solarized
 6:46          solarized
```

When opening vim (it is currently 19:00 in Germany and pitch-black dark outside, I still get the light variant of Solarized. Switching the tow times instead gives me the dark one.

What could be the reason here?

**Comment by nightsense** [comment] 2017-10-29 21:49
Thanks @themightyoarfish, I think the problem is fixed now, let me know if you have any further issues. I  also added the background value (dark/light) to the NdSchedule output to avoid ambiguity between entries.

**Closed** 2017-11-07 16:48 UTC
